---
# include some reasonable defaults for module paths
sm_prefix: "/sw"
sm_module_root: "{{ sm_prefix }}/modules"
sm_module_path: "{{ sm_module_root }}/all"
sm_software_path: "{{ sm_prefix }}/software"
