---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution|lower }}.yml"
      - "{{ ansible_os_family|lower }}.yml"
      paths:
      - ../vars
      skip: true
  tags:
    - always

- name: add epel repo
  yum:
    name: 
      - "{{ epel_package }}"
    state: latest
  when: ansible_os_family == "RedHat"
