---
- name: add epel repo
  yum:
    name: 
      - "epel-release"
    state: latest

- name: add repo
  yum_repository:
    name: machine-learning
    description: NVIDIA Machine Learning YUM Repo
    gpgkey: "{{ rhel_nvidiaml_gpgkey }}"
    baseurl: "{{ rhel_nvidiaml_baseurl }}"
