apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: admission-webhook-cert
spec:
  isCA: true
  commonName: $(serviceName).$(namespace).svc
  dnsNames:
  - $(serviceName).$(namespace).svc
  - $(serviceName).$(namespace).svc.dgxtd.trace3.com
  issuerRef:
    kind: ClusterIssuer
    name: $(issuer)
  secretName: webhook-certs